swagger: "2.0"
info:
  title: Tupsiregister
  version: 1.0.0
  description: Vali oma lemmik tups
paths:
  /tups:
    get:
      tags:
        - Tups
      responses:
        "200":
          description: Returns a list of Tups
          schema:
            type: array
            items:
              type: string
          examples:
            application/json:
              - Velo
              - Killa
              - Odens
      summary: Get all the <tups> in API
      description: Return all Tups that are registered in API
    post:
      tags:
        - Tups
      parameters:
        - name: body
          description: The <Tups> that is to be created.
          schema:
            $ref: "#/definitions/new-Tups"
          in: body
          required: true
      responses:
        "201":
          description: Send 201 when <Tups> is successfully added to the database
          schema:
            $ref: "#/definitions/new-Tups"
          examples:
            application/json:
              Name: NewTupsName
              Description: NewTupsDescription
              Brand: NewTupsBrandName
              Strength: "10"
        "400":
          description: "Missing some parameter, please review your request data"
          schema:
            $ref: "#/definitions/error"
      summary: Create a new <Tups> into the app
      description: "Creates a new <Tups> instance with its required details, for further usage."
  "/tups/{TupsID}":
    get:
      tags:
        - Tups
      responses:
        "200": {}
        "404":
          schema:
            $ref: "#/definitions/error"
      operationId: TupsID
      summary: Get the full details of a Tups
      description: Will return all details of a given <Tups> based on TupsID given.
    delete:
      tags:
        - Tups
      parameters:
        - name: body
          description: ID of <Tups> to be removed from the app
          schema:
            $ref: "#/definitions/delete-Tups"
          in: body
          required: true
      responses:
        "204":
          description: Returns  "No content" when removal of <Tups> is sucess
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: No Content
        "404":
          description: "Returns error, when <Tups> with specified ID does not exist"
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: ID not found
      summary: Delete a <Tups> from the app
      description: Deletes an entry from the app
    parameters:
      - name: TupsID
        description: ID of Tups
        in: path
        required: true
        type: string
definitions:
  error:
    title: Root Type for error
    description: ""
    type: object
    properties:
      error:
        type: string
    example:
      error: Error message
  new-Tups:
    title: Root Type for new-Tups
    description: ""
    required:
      - Brand
      - Description
      - Name
      - Strength
    type: object
    properties:
      Name:
        type: string
      Description:
        type: string
      Brand:
        type: string
      Strength:
        format: float
        type: number
    example:
      Name: NewTupsName
      Description: NewTupsDescription
      Brand: NewTupsBrandName
      Strength: "10"
  delete-Tups:
    title: Root Type for delete-Tups
    description: ""
    type: object
    properties:
      TupsID:
        type: string
    example:
      TupsID: 5f9b9e90-cec3-11f0-b43f-901b0eec5991
