swagger: "2.0"
info:
  title: Tupsiregister
  version: 1.0.0
  description: Vali oma lemmik tups
paths:
  /tups:
    get:
      tags:
        - tups
      responses:
        "200":
          description: Returns a list of Tups
          schema:
            type: array
            items:
              type: string
          examples:
            application/json:
              - Velo
              - Killa
              - Odens
      summary: Get all the <tups> in API
      description: Return all Tups that are registered in API
  "/tups/{TupsID}":
    get:
      responses:
        "200": {}
        "404":
          schema:
            $ref: "#/definitions/error"
      summary: Get the full details of a Tups
      description: Will return all details of a given <Tups> based on TupsID given.
definitions:
  error:
    title: Root Type for error
    description: ""
    type: object
    properties:
      error:
        type: string
    example:
      error: Error message
