swagger: "2.0"
info:
  title: Tupsiregister
  version: 1.0.0
  description: Vali oma lemmik tups
paths:
  /tups:
    get:
      tags:
        - Tups
      responses:
        "200":
          description: Returns a list of Tups
          schema:
            type: array
            items:
              type: string
          examples:
            application/json:
              - Velo
              - Killa
              - Odens
      summary: Get all the <tups> in API
      description: Return all Tups that are registered in API
    post:
      tags:
        - Tups
      parameters:
        - name: body
          description: The <Tups> that is to be created.
          schema:
            $ref: "#/definitions/new-Tups"
          in: body
          required: true
      responses:
        "201":
          description: Send 201 when <Tups> is successfully added to the database
          schema:
            $ref: "#/definitions/new-Tups"
          examples:
            application/json:
              Name: NewTupsName
              Description: NewTupsDescription
              Brand: NewTupsBrandName
              Strength: Strength
        "400":
          description: "Missing some parameter, please review your request data"
          schema:
            $ref: "#/definitions/error"
      summary: Create a new <Tups> into the app
      description: "Creates a new <Tups> instance with its required details, for further usage."
  "/tups/{TupsID}":
    get:
      tags:
        - Tups
      responses:
        "200": {}
        "404":
          schema:
            $ref: "#/definitions/error"
      summary: Get the full details of a Tups
      description: Will return all details of a given <Tups> based on TupsID given.
definitions:
  error:
    title: Root Type for error
    description: ""
    type: object
    properties:
      error:
        type: string
    example:
      error: Error message
  new-Tups:
    title: Root Type for new-Tups
    description: ""
    required:
      - Brand
      - Description
      - Name
      - Strength
    type: object
    properties:
      Name:
        type: string
      Description:
        type: string
      Brand:
        type: string
      Strength:
        format: float
        type: number
    example:
      Name: NewTupsName
      Description: NewTupsDescription
      Brand: NewTupsBrandName
      Strength: Strength
